### ISSUE TITLE
Diagrama de secuencia y de clase

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-9-diagrama-de-clases-secuencia-equipo-v-a-k#1]
[Reporte diagrama de Clases y de secuencias.pdf](https://github.com/user-attachments/files/18043100/Reporte.diagrama.de.Clases.y.de.secuencias.pdf)

DIAGRAMA DE CLASE:
https://github.com/SistemasTecTlaxiaco/Loc-Serv/wiki/11-Arquitectura-de-Software-para-Web-3.0#3-diagrama-de-clases
DIAGRAMA DE SECUENCIA:
https://github.com/SistemasTecTlaxiaco/Loc-Serv/wiki/11-Arquitectura-de-Software-para-Web-3.0#4-diagrama-de-secuencia

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rubrica tiene 28 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
